# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crewd < Formula
  desc "The package manager for prompt-defined AI agents, skills, and teams"
  homepage "https://crewd.dev"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.1/crewd_Darwin_x86_64.tar.gz"
      sha256 "1744c583979ba4918068ea6953bfbc94131229333cf6f3c857f7f3f30ac2d8f6"

      define_method(:install) do
        bin.install "crewd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.1/crewd_Darwin_arm64.tar.gz"
      sha256 "61e8bd491d79c3c9e96788191f60c3c68a52c1a45126c2cfa97fa3a78aad3ccc"

      define_method(:install) do
        bin.install "crewd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.1/crewd_Linux_x86_64.tar.gz"
      sha256 "dcfb7145cfea7f1c464378c3dc98569a96c6a278ebec00c155f666a4ea6c6019"
      define_method(:install) do
        bin.install "crewd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.1/crewd_Linux_arm64.tar.gz"
      sha256 "2fd26b5bd4a0e09eef20dbbe18e3c2408aef6616bdf63b17201a7aa9a658be8b"
      define_method(:install) do
        bin.install "crewd"
      end
    end
  end

  test do
    system "#{bin}/crewd version"
  end
end
