# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrewdCli < Formula
  desc "The package manager for prompt-defined AI agents, skills, and teams"
  homepage "https://crewd.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crewdhq/crewd-cli/releases/download/v0.1.0/crewd-cli_Darwin_x86_64.tar.gz"
      sha256 "2afd935ec76e0a8b9aae763e023d44615a7b2e97caf1fc89a6ce0fd9be512cb5"

      define_method(:install) do
        bin.install "crewd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crewdhq/crewd-cli/releases/download/v0.1.0/crewd-cli_Darwin_arm64.tar.gz"
      sha256 "9590691d98026a9515663db5b5a37cf0c84ab8a2ebd04ed1597d3936fa19e8d7"

      define_method(:install) do
        bin.install "crewd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crewdhq/crewd-cli/releases/download/v0.1.0/crewd-cli_Linux_x86_64.tar.gz"
      sha256 "928aacbadca0d6870037a4380df8135f6db243855fa506902e0d8e673019ac62"
      define_method(:install) do
        bin.install "crewd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crewdhq/crewd-cli/releases/download/v0.1.0/crewd-cli_Linux_arm64.tar.gz"
      sha256 "0e6c7fdbde6cc4bde46f1164f772dda8c227c8522f460f68af056a92224346c9"
      define_method(:install) do
        bin.install "crewd"
      end
    end
  end

  test do
    system "#{bin}/crewd version"
  end
end
