# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crewd < Formula
  desc "The package manager for prompt-defined AI agents, skills, and teams"
  homepage "https://crewd.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.0/crewd_Darwin_x86_64.tar.gz"
      sha256 "45916324a5b6a8441dcc96878d9cc71b6ca1b28389021dc1c0c2d86097e828c7"

      define_method(:install) do
        bin.install "crewd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.0/crewd_Darwin_arm64.tar.gz"
      sha256 "37e21a798a3c05cd5a9748d25fcfb1a7736d2388e4f3b10ae4dd410881abcdcb"

      define_method(:install) do
        bin.install "crewd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.0/crewd_Linux_x86_64.tar.gz"
      sha256 "b34a7bd527bf8f56cb33e33cb51ba142521fc8b9fcbdce578284075094b9caa1"
      define_method(:install) do
        bin.install "crewd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.0/crewd_Linux_arm64.tar.gz"
      sha256 "42db946a3900bea210ba0957a83699a415855d7869bf9c3926b79473198946f4"
      define_method(:install) do
        bin.install "crewd"
      end
    end
  end

  test do
    system "#{bin}/crewd version"
  end
end
