# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crewd < Formula
  desc "The package manager for prompt-defined AI agents, skills, and teams"
  homepage "https://crewd.dev"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.2/crewd_Darwin_x86_64.tar.gz"
      sha256 "14251bc291bb1b3a48a6e7f6827be72e28ace205ec6f51c60351f2b5dc6016cc"

      define_method(:install) do
        bin.install "crewd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.2/crewd_Darwin_arm64.tar.gz"
      sha256 "90514279b66415bfaa34faa370adc38d329e583f077482f7e77a3583ab3bcb25"

      define_method(:install) do
        bin.install "crewd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.2/crewd_Linux_x86_64.tar.gz"
      sha256 "50e400b4257ee1eb9bfa730128f36e2b241f9de6038c9d9e621a94b53f6df7ec"
      define_method(:install) do
        bin.install "crewd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crewdhq/homebrew-tap/releases/download/v0.1.2/crewd_Linux_arm64.tar.gz"
      sha256 "7f0432994046e88e96a2ae9ba7acfbba4ae4bd31e18f07d6791872e6c9193eab"
      define_method(:install) do
        bin.install "crewd"
      end
    end
  end

  test do
    system "#{bin}/crewd version"
  end
end
